on:
  push:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
      - name: Publish (master-branch only)
        uses: timo-reymann/docker-semantic-release-gh-action@v1
        if: false # && github.ref == 'refs/heads/master'
        with:
          image: nutgaard/rest-api-mock
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
